-- quiz_full.sql  (run on web-app: slzzzbptquemazhhpekr)
-- Emits ONE pipe-delimited CSV cell: latest web quiz per sequenced person, single-selects as codes,
-- key multi-selects exploded into binary flags. Paste into milieu_signal_explorer.html -> id="QUIZ".
-- IF THE RESULT EXCEEDS THE MCP SIZE LIMIT: wrap `latest` with ntile and run per bucket, e.g.
--   nb AS (SELECT *, ntile(2) OVER (ORDER BY profile_id) b FROM latest)  ... WHERE b=1  (then b=2).
-- Always coalesce value/answer. Multi-select values are stringified arrays -> match with ILIKE '%TOKEN%'.
WITH latest AS (
  SELECT DISTINCT ON (qs.profile_id) qs.profile_id, qs.quiz_data d, lower(p.email) email
  FROM quiz_submissions qs
  JOIN raw_microbiome_data r ON r.id=qs.profile_id AND r.full_taxa IS NOT NULL AND r.diversity IS NOT NULL
  JOIN profiles p ON p.id=qs.profile_id
  WHERE p.email IS NOT NULL
  ORDER BY qs.profile_id, qs.created_at DESC)
SELECT 'email|alcohol|caffeine|sugar|dairy|meat|seafood|processed|dessert|fruitsveg|carbs|diet|stress|sleepcons|sleephrs|screen|water|sunexp|sunscreen|pollution|facetouch|nailchew|bedding|hygiene|antimicro|showerdry|makeup|exfolfreq|proftreat|probiotic|animal|living|fitz|skinpattern|cleansefeel|goal|acnetriage|breakoutapp|menstrual|lifestage|hormonesupp|reacthist|scarring|pasttreat|med_antibiotics|med_accutane|med_hormonalbc|med_cortico|med_glp1|med_mood|cond_eczema|cond_rosacea|cond_fungalacne|cond_dermatitis|cond_psoriasis|cond_melasma|fam_eczema|fam_acne|fam_rosacea|fam_psoriasis|shower_hot|shower_long|shower_antibac|shower_multi|env_humid|env_dry|env_ac|env_heated|env_windy|sens_irritated|sens_dryness|sens_stinging|tobacco_any|pore_clogged|pore_enlarged|pore_oily|eth_white|eth_eastasian|eth_southasian|eth_black|eth_hispanic|eth_mideast' || E'\n' ||
string_agg(concat_ws('|', email,
 coalesce(d->'alcohol_consumption'->>'value',d->'alcohol_consumption'->>'answer',''),
 coalesce(d->'caffeine_consumption'->>'value',d->'caffeine_consumption'->>'answer',''),
 coalesce(d->'sugar_consumption'->>'value',d->'sugar_consumption'->>'answer',''),
 coalesce(d->'dairy_consumption'->>'value',d->'dairy_consumption'->>'answer',''),
 coalesce(d->'meat_consumption'->>'value',d->'meat_consumption'->>'answer',''),
 coalesce(d->'seafood_consumption'->>'value',d->'seafood_consumption'->>'answer',''),
 coalesce(d->'processed_food_consumption'->>'value',d->'processed_food_consumption'->>'answer',''),
 coalesce(d->'dessert_consumption'->>'value',d->'dessert_consumption'->>'answer',''),
 coalesce(d->'fruits_vegetables_servings'->>'value',d->'fruits_vegetables_servings'->>'answer',''),
 coalesce(d->'carbohydrate_intake'->>'value',d->'carbohydrate_intake'->>'answer',''),
 coalesce(d->'typical_diet'->>'value',d->'typical_diet'->>'answer',''),
 coalesce(d->'stress_levels'->>'value',d->'stress_levels'->>'answer',''),
 coalesce(d->'sleep_consistency'->>'value',d->'sleep_consistency'->>'answer',''),
 coalesce(d->'sleep_hours'->>'value',d->'sleep_hours'->>'answer',''),
 coalesce(d->'screen_time'->>'value',d->'screen_time'->>'answer',''),
 coalesce(d->'daily_water_intake'->>'value',d->'daily_water_intake'->>'answer',''),
 coalesce(d->'daily_sun_exposure'->>'value',d->'daily_sun_exposure'->>'answer',''),
 coalesce(d->'sunscreen_frequency'->>'value',d->'sunscreen_frequency'->>'answer',''),
 coalesce(d->'pollution_exposure'->>'value',d->'pollution_exposure'->>'answer',''),
 coalesce(d->'face_touching_habits'->>'value',d->'face_touching_habits'->>'answer',''),
 coalesce(d->'nail_chewing'->>'value',d->'nail_chewing'->>'answer',''),
 coalesce(d->'bedding_hygiene'->>'value',d->'bedding_hygiene'->>'answer',''),
 coalesce(d->'hygiene_habits'->>'value',d->'hygiene_habits'->>'answer',''),
 coalesce(d->'antimicrobial_use_frequency'->>'value',d->'antimicrobial_use_frequency'->>'answer',''),
 coalesce(d->'shower_dryness_followup'->>'value',d->'shower_dryness_followup'->>'answer',''),
 coalesce(d->'makeup_frequency'->>'value',d->'makeup_frequency'->>'answer',''),
 coalesce(d->'exfoliation_frequency'->>'value',d->'exfoliation_frequency'->>'answer',''),
 coalesce(d->'professional_treatment_frequency'->>'value',d->'professional_treatment_frequency'->>'answer',''),
 coalesce(d->'probiotic_consumption'->>'value',d->'probiotic_consumption'->>'answer',''),
 coalesce(d->'animal_contact'->>'value',d->'animal_contact'->>'answer',''),
 coalesce(d->'living_situation'->>'value',d->'living_situation'->>'answer',''),
 coalesce(d->'fitzpatrick_skin_type'->>'value',d->'fitzpatrick_skin_type'->>'answer',''),
 coalesce(d->'skin_pattern'->>'value',d->'skin_pattern'->>'answer',''),
 coalesce(d->'cleansing_feel'->>'value',d->'cleansing_feel'->>'answer',''),
 coalesce(d->'primary_goal'->>'value',d->'primary_goal'->>'answer',''),
 coalesce(d->'acne_triage'->>'value',d->'acne_triage'->>'answer',''),
 coalesce(d->'breakout_appearance'->>'value',d->'breakout_appearance'->>'answer',''),
 coalesce(d->'menstrual_cycle_breakouts'->>'value',d->'menstrual_cycle_breakouts'->>'answer',''),
 coalesce(d->'life_stage'->>'value',d->'life_stage'->>'answer',''),
 coalesce(d->'hormone_supplements'->>'value',d->'hormone_supplements'->>'answer',''),
 coalesce(d->'skincare_reaction_history'->>'value',d->'skincare_reaction_history'->>'answer',''),
 coalesce(d->'scarring_concerns'->>'value',d->'scarring_concerns'->>'answer',''),
 coalesce(d->'past_treatments'->>'value',d->'past_treatments'->>'answer',''),
 CASE WHEN coalesce(d->'recent_medications'->>'value',d->'recent_medications'->>'answer','') ILIKE '%ANTIBIOTICS%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'recent_medications'->>'value',d->'recent_medications'->>'answer','') ILIKE '%ACCUTANE%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'recent_medications'->>'value',d->'recent_medications'->>'answer','') ILIKE '%HORMONAL_BI%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'recent_medications'->>'value',d->'recent_medications'->>'answer','') ILIKE '%CORTICOSTEROID%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'recent_medications'->>'value',d->'recent_medications'->>'answer','') ILIKE '%GLP1%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'recent_medications'->>'value',d->'recent_medications'->>'answer','') ILIKE '%MOOD_MEDICA%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'diagnosed_conditions'->>'value',d->'diagnosed_conditions'->>'answer','') ILIKE '%ECZEMA%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'diagnosed_conditions'->>'value',d->'diagnosed_conditions'->>'answer','') ILIKE '%ROSACEA%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'diagnosed_conditions'->>'value',d->'diagnosed_conditions'->>'answer','') ILIKE '%FUNGAL_ACNE%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'diagnosed_conditions'->>'value',d->'diagnosed_conditions'->>'answer','') ILIKE '%DERMATITIS%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'diagnosed_conditions'->>'value',d->'diagnosed_conditions'->>'answer','') ILIKE '%PSORIASIS%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'diagnosed_conditions'->>'value',d->'diagnosed_conditions'->>'answer','') ILIKE '%MELASMA%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'family_history'->>'value',d->'family_history'->>'answer','') ILIKE '%ECZEMA%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'family_history'->>'value',d->'family_history'->>'answer','') ILIKE '%ACNE%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'family_history'->>'value',d->'family_history'->>'answer','') ILIKE '%ROSACEA%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'family_history'->>'value',d->'family_history'->>'answer','') ILIKE '%PSORIASIS%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'shower_habits'->>'value',d->'shower_habits'->>'answer','') ILIKE '%VERY_HOT%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'shower_habits'->>'value',d->'shower_habits'->>'answer','') ILIKE '%LONG_15%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'shower_habits'->>'value',d->'shower_habits'->>'answer','') ILIKE '%ANTIBACTERIAL%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'shower_habits'->>'value',d->'shower_habits'->>'answer','') ILIKE '%MULTIPLE_TIMES%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'environmental_conditions'->>'value',d->'environmental_conditions'->>'answer','') ILIKE '%HUMID%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'environmental_conditions'->>'value',d->'environmental_conditions'->>'answer','') ILIKE '%DRY_ENV%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'environmental_conditions'->>'value',d->'environmental_conditions'->>'answer','') ILIKE '%AIR_CONDITIONED%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'environmental_conditions'->>'value',d->'environmental_conditions'->>'answer','') ILIKE '%HEATED%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'environmental_conditions'->>'value',d->'environmental_conditions'->>'answer','') ILIKE '%WINDY%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'sensitivity_signs'->>'value',d->'sensitivity_signs'->>'answer','') ILIKE '%IRRITATED%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'sensitivity_signs'->>'value',d->'sensitivity_signs'->>'answer','') ILIKE '%PERSISTENT_DRYNESS%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'sensitivity_signs'->>'value',d->'sensitivity_signs'->>'answer','') ILIKE '%STINGING%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'tobacco_exposure'->>'value',d->'tobacco_exposure'->>'answer','') ILIKE '%DIRECT%' OR coalesce(d->'tobacco_exposure'->>'value',d->'tobacco_exposure'->>'answer','') ILIKE '%SECONDHAND%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'pores_oil_production'->>'value',d->'pores_oil_production'->>'answer','') ILIKE '%CLOGGED%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'pores_oil_production'->>'value',d->'pores_oil_production'->>'answer','') ILIKE '%ENLARGED%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'pores_oil_production'->>'value',d->'pores_oil_production'->>'answer','') ILIKE '%EXCESSIVE_OILINESS%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'ethnic_background'->>'value',d->'ethnic_background'->>'answer','') ILIKE '%WHITE_EUROP%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'ethnic_background'->>'value',d->'ethnic_background'->>'answer','') ILIKE '%EAST_ASIAN%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'ethnic_background'->>'value',d->'ethnic_background'->>'answer','') ILIKE '%SOUTH_ASIAN%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'ethnic_background'->>'value',d->'ethnic_background'->>'answer','') ILIKE '%BLACK_AFRICAN%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'ethnic_background'->>'value',d->'ethnic_background'->>'answer','') ILIKE '%HISPANIC%' THEN '1' ELSE '0' END,
 CASE WHEN coalesce(d->'ethnic_background'->>'value',d->'ethnic_background'->>'answer','') ILIKE '%MIDDLE_EAST%' THEN '1' ELSE '0' END
), E'\n') AS csv
FROM latest;
